name: Run basic linting and testing

on:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2

      - name: ESLint
        run: yarn run eslint

  test:
    needs: lint
    strategy:
      matrix:
        version: [12, 14, 16, 18]
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.version }}

      - name: Run tests
        run: yarn run test
